apiVersion: v1
kind: Namespace
metadata:
  name: ks-load
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-service
  namespace: ks-load
spec:
  replicas: 3               # Number of httpd servers
  selector:
    matchLabels:
      app: httpd-service
  template:
    metadata:
      labels:
        app: httpd-service
    spec:
      containers:
      - name: httpd
        image: alongir/ks-load-httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: ks-load
spec:
  selector:
    app: httpd-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-load-test
  namespace: ks-load
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: k6-load-test
  template:
    metadata:
      labels:
        app: k6-load-test
    spec:
      containers:
      - name: k6
        image: alongir/k6-loadtest:latest
        env:
          - name: VUS
            value: "100"
          - name: DURATION
            value: "3h"
          - name: URL
            value: "http://httpd-service.ks-load.svc.cluster.local/smap.png"
          - name: SLEEP
            value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: k6-load-test
  namespace: ks-load
spec:
  selector:
    app: k6-load-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
